services:
  database:
    image: postgres:17.5-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres/data

  server:
    build:
      context: .
      args:
        BUILD_PROFILE: ${BUILD_PROFILE}
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - ${SERVER_PORT}:8080
    depends_on:
      - database
